export const ADD_REMINDER = 'ADD_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const DELETE_ALL_REMINDERS = 'DELETE_ALL_REMINDERS';
export const GET_RANDOM_IMAGE = 'GET_RANDOM_IMAGE';
export const RECEIVE_RANDOM_IMAGE = 'RECEIVE_RANDOM_IMAGE';